#!/usr/bin/env python3

from pathlib import Path
import argparse
import json
import re

# maybe change from hardcoded?
template_file = Path(__file__).parent / "head.tex"

def main():
    p = argparse.ArgumentParser()
    p.add_argument("datafile")

    args = p.parse_args()

    datafile = Path(args.datafile) 

    with datafile.open() as fh:
        data = json.load(fh)

    template = template_file.read_text()

    def rep(m):
        s, = m.groups()
        if not s.startswith("cookiecutter."):
            raise ValueError("Unknown variable")
        _, k = s.split(".", 1)
        return data[k]

    out = re.sub(r" *{{-? ?([\w\.-_]+) ?-?}} *", rep, template)

    print("% THIS FILE IS AUTOGENERATED! EDIT WITH CAUTION")
    print(out)




if __name__ == "__main__":
    main()
    
